name: Update team permissions
on: [workflow_dispatch,workflow_call,push]
        
jobs:
  check-topics:
    runs-on: ubuntu-latest
    outputs:
      customer_private: ${{ steps.check_private.outputs.is-private }}
    steps:
      - name: GitHub Script checks for topics array containing kf-customer-private
        id: check_private
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            // check for existing topics on this major.minor version
            const topics = await github.rest.repos.getAllTopics({
            owner: context.repo.owner,
            repo: context.repo.repo,
            });
            console.log(topics.data.names)
            const size = topics.data.names.length;
            console.log(`Length: ${size}`);
            const pos = topics.data.names.indexOf('kf-customer-private')
            console.log(`Position: ${pos}`);
            var IS_PRIVATE=
            (topics.length > 0 && topics.data.names.indexOf('kf-customer-private') > 0) ? IS_PRIVATE='T' : IS_PRIVATE='F'
            core.exportVariable('IS_PRIVATE', `${IS_PRIVATE}`);
            console.log(`IS_PRIVATE = ${IS_PRIVATE}`);
            
      - name: Debugging Step
        id: debug_step
        if: env.IS_PRIVATE != 'T'
        run: |
          echo IS_PRIVATE = ${IS_PRIVATE}

      - name: GitHub Script configures teams if not private
        id: update_teams
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION_NUMBER: ${{ env.RELEASE_VERSION }}
        if: env.IS_PRIVATE != 'T'
        with:
          script: |
            console.log(`This is the step where the teams get updated`);
            console.log('That is next');

 
