name: Update team permissions
on: [workflow_dispatch,workflow_call,push]
        
jobs:
  check-topics:
    runs-on: ubuntu-latest
    outputs:
      customer_private: ${{ steps.check_private.outputs.is-private }}
    steps:
      - name: GitHub Script checks for topics array containing kf-customer-private
        id: check_private
        uses: actions/github-script@v6
        with:
          script: |
            // check for existing topics on this major.minor version
            const topics = await github.rest.repos.getAllTopics({
            owner: context.repo.owner,
            repo: context.repo.repo,
            });
            const size = topics.data.names.length;
            const pos = topics.data.names.indexOf('kf-customer-private')
            var IS_PRIVATE=
            (size > 0 && pos > 0) ? IS_PRIVATE='T' : IS_PRIVATE='F'
            core.exportVariable('IS_PRIVATE', `${IS_PRIVATE}`);
            
      - name: GitHub Script configures teams if not private
        id: update_team
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: env.IS_PRIVATE != 'T'
        with:
          script: |
            console.log('noop')

      - name: GitHub Script configures teams if not private
        id: update_teams
        uses: actions/github-script@v6
        if: env.IS_PRIVATE != 'T'
        with:
          github-token: ${{ secrets.TEST_ACTION_GH_PAT }}
          script: |
            const teams = [ // Using array of arrays because team names contain hyphen character, illegal json
            ["field-software-engineers", "push"],
            ["integration-engineers", "push"],
            ["private-access", "pull"],
            ["release_builders", "admin"]
            ];
            const repo = context.repo.repo;
            const org = context.repo.owner;
            const owner = org;
            teams.forEach(element => {
              console.log(element[0] + ' : ' + element[1])
              const team_slug = element[0];
              const permission = element[1];
              console.log(`org: ${org}\nteam_slug: ${team_slug}\npermission: ${permission}\nowner: ${owner}\nrepo ${repo}`)
              github.rest.teams.addOrUpdateRepoPermissionsInOrg({
                org,
                team_slug,
                owner,
                repo,
              });
             });

